name: Learn-github-workflows
on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrts.GITHUB_TOKEN }}

