name: Learn-github-workflows
on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
          prerelease: true

